name: CI - React Native SDK

on:
  push:
    branches:
      - main
    paths:
      - 'pulse-react-native-otel/**'
      - '.github/workflows/ci-react-native.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'pulse-react-native-otel/**'
      - '.github/workflows/ci-react-native.yml'
  merge_group:
    types:
      - checks_requested

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version-file: pulse-react-native-otel/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
            ${{ runner.os }}-yarn-rn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: pulse-react-native-otel
        run: yarn install --immutable

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}

      - name: Lint files
        working-directory: pulse-react-native-otel
        run: yarn lint

      - name: Typecheck files
        working-directory: pulse-react-native-otel
        run: yarn typecheck

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version-file: pulse-react-native-otel/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
            ${{ runner.os }}-yarn-rn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: pulse-react-native-otel
        run: yarn install --immutable

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}

      - name: Run unit tests
        working-directory: pulse-react-native-otel
        run: yarn test --maxWorkers=2 --coverage

  build-library:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version-file: pulse-react-native-otel/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
            ${{ runner.os }}-yarn-rn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: pulse-react-native-otel
        run: yarn install --immutable

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}

      - name: Build package
        working-directory: pulse-react-native-otel
        run: yarn prepare

  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    env:
      TURBO_CACHE_DIR: .turbo/android

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version-file: pulse-react-native-otel/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
            ${{ runner.os }}-yarn-rn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: pulse-react-native-otel
        run: yarn install --immutable

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}

      - name: Cache turborepo for Android
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: pulse-react-native-otel/${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-android-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-android-

      - name: Check turborepo cache for Android
        working-directory: pulse-react-native-otel
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:android --cache-dir=".turbo/android" --dry=json)).tasks.find(t => t.task === 'build:android').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Install JDK
        if: env.turbo_cache_hit != 1
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00  # v4.7.1
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Finalize Android SDK
        if: env.turbo_cache_hit != 1
        run: |
          /bin/bash -c "yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses > /dev/null"

      - name: Cache Gradle
        if: env.turbo_cache_hit != 1
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            ~/.gradle/wrapper
            ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('pulse-react-native-otel/example/android/gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build example for Android
        working-directory: pulse-react-native-otel
        env:
          JAVA_OPTS: "-XX:MaxHeapSize=6g"
        run: |
          yarn turbo run build:android --cache-dir=".turbo/android"

  build-ios:
    runs-on: macos-latest
    permissions:
      contents: read

    env:
      XCODE_VERSION: 16.3
      TURBO_CACHE_DIR: .turbo/ios
      RCT_USE_RN_DEP: 1
      RCT_USE_PREBUILT_RNCORE: 1

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4.4.0
        with:
          node-version-file: pulse-react-native-otel/.nvmrc

      - name: Restore dependencies
        id: yarn-cache
        uses: actions/cache/restore@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
            ${{ runner.os }}-yarn-rn-

      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        working-directory: pulse-react-native-otel
        run: yarn install --immutable

      - name: Cache dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        uses: actions/cache/save@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: |
            pulse-react-native-otel/**/node_modules
            pulse-react-native-otel/.yarn/install-state.gz
          key: ${{ runner.os }}-yarn-rn-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}-${{ hashFiles('pulse-react-native-otel/package.json') }}

      - name: Cache turborepo for iOS
        uses: actions/cache@5a3ec84eff668545956fd18022155c47e93e2684  # v4.2.3
        with:
          path: pulse-react-native-otel/${{ env.TURBO_CACHE_DIR }}
          key: ${{ runner.os }}-turborepo-ios-${{ hashFiles('pulse-react-native-otel/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-turborepo-ios-

      - name: Check turborepo cache for iOS
        working-directory: pulse-react-native-otel
        run: |
          TURBO_CACHE_STATUS=$(node -p "($(yarn turbo run build:ios --cache-dir=".turbo/ios" --dry=json)).tasks.find(t => t.task === 'build:ios').cache.status")

          if [[ $TURBO_CACHE_STATUS == "HIT" ]]; then
            echo "turbo_cache_hit=1" >> $GITHUB_ENV
          fi

      - name: Use appropriate Xcode version
        if: env.turbo_cache_hit != 1
        uses: maxim-lobanov/setup-xcode@60606e260d2fc5762a71e64e74b2174e8ea3c8bd  # v1.6.0
        with:
          xcode-version: ${{ env.XCODE_VERSION }}

      - name: Install cocoapods
        if: env.turbo_cache_hit != 1
        working-directory: pulse-react-native-otel/example
        run: |
          bundle install
          bundle exec pod repo update --verbose
          bundle exec pod install --project-directory=ios

      - name: Build example for iOS
        working-directory: pulse-react-native-otel
        run: |
          yarn turbo run build:ios --cache-dir=".turbo/ios"

